### ISSUE TITLE
Не создаёт метод. 

### ISSUE THREAD

**Issue by ghost** [pafnuty/pcp-cs-admin#5]
Здравствуйте! 
Не могу создать метод в вашей админке. Форма при добавлении просто зависает и ничего не добавляет!

**Comment by pafnuty** [comment]
Здравствуйте!
Возможно есть js-ошибка, что пишет в консоли?

**Comment by ghost** [comment]
Как таковой консоли мой хостинг не поддерживает. Если это поможет, вот доступ к админке browserload.ru - 123maks:admin (лог:пасс)

**Comment by ghost** [comment]
Понял,вы про бразуерную. Завтра тогда посмотрю. Нет доступа к компьютеру

**Comment by pafnuty** [comment]
имелась ввиду консоль браузера.
Судя по всему у вас не настроено соединение с БД или нет таблиц.

**Comment by ghost** [comment]
Хорошо, тогда попробую поискать в файлах конфига. Таблицы все есть.
